# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT
#

# Поддержка энкодеров
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Увеличенный debounce
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=2
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=2

# Увеличенный лимит комбо для Shift
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=20

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=240
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=10
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=1
CONFIG_ZMK_RGB_UNDERGLOW_SAT_STEP=1
CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=1
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# OLED 128x32 (SSD1306, I2C 0x3C) — shield Sofle
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

CONFIG_ZMK_IDLE_TIMEOUT=180000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Экспериментальные BLE-настройки для лучшей производительности
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
